GET http://localhost:5000/task
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBoYW50b20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTkyNjA4MDZ9.RTh1bqrpDZZalGEpj2HnjovGZiHSOYBW4f5RWfELLmg

###
POST http://localhost:5000/task
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBoYW50b20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTkyNjA4MDZ9.RTh1bqrpDZZalGEpj2HnjovGZiHSOYBW4f5RWfELLmg

Content-Type: application/json

    {
        "name": "test",
        "description": "test",
    }
